version: 2
updates:
  # Maintain dependencies for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10
    reviewers:
      - "yoges"
    labels:
      - "dependencies"
      - "security"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    labels:
      - "ci"
      - "dependencies"
