import React from 'react';
import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { NavBar } from '@/components/layout/NavBar';
import { AnnouncementBar } from '@/components/layout/AnnouncementBar';
import { Footer } from '@/components/layout/Footer';
import { ShieldCheck, FileText, Lock, RefreshCw, Mail, Phone, MapPin } from 'lucide-react';

export const metadata = {
  title: 'Privacy Policy | Blessing Power Guide',
  description: 'Privacy policy and data security practices for Blessing Power Guide Publications.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-800" style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>
      <AnnouncementBar />
      <Header />
      <NavBar />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
        <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-10 shadow-xs space-y-8">
          <div className="border-b border-slate-100 pb-6">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-50 text-[#2874f0] rounded-full text-xs font-bold uppercase tracking-wider mb-3">
              <ShieldCheck className="w-4 h-4" /> Legal & Data Protection
            </div>
            <h1 className="font-black text-2xl sm:text-3xl text-slate-900">Privacy Policy</h1>
            <p className="text-xs text-slate-500 mt-1">Last updated: January 2026 • Blessing Pathway Education (OPC) Pvt Ltd</p>
          </div>

          <section className="space-y-4 text-xs sm:text-sm leading-relaxed text-slate-600">
            <h2 className="font-bold text-base text-slate-900 flex items-center gap-2">
              <Lock className="w-4 h-4 text-[#2874f0]" /> 1. Information We Collect
            </h2>
            <p>
              When you purchase educational guide books or create an account on Blessing Power Guide (blessingpowerguide.in), we collect essential user details necessary to process orders and deliver shipments across India:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Full Name and Contact Number (for courier SMS and delivery updates)</li>
              <li>Delivery Address, District, State, and Postal Pincode</li>
              <li>Email address (for account verification and digital receipt invoices)</li>
              <li>Payment verification tokens generated by Razorpay (we never store plain credit card or UPI PINs)</li>
            </ul>
          </section>

          <section className="space-y-4 text-xs sm:text-sm leading-relaxed text-slate-600">
            <h2 className="font-bold text-base text-slate-900 flex items-center gap-2">
              <FileText className="w-4 h-4 text-[#2874f0]" /> 2. How We Use Your Data
            </h2>
            <p>
              Your personal information is strictly used for order fulfillment, dispatching parcels via our official courier partner (ST Courier Express), providing real-time tracking updates over automated WhatsApp messages, and assisting customer support inquiries.
            </p>
          </section>

          <section className="space-y-4 text-xs sm:text-sm leading-relaxed text-slate-600">
            <h2 className="font-bold text-base text-slate-900 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-[#2874f0]" /> 3. Data Protection & Security
            </h2>
            <p>
              We enforce HTTPS/TLS encryption across all API endpoints and database connections. Your data is stored on secure Railway PostgreSQL instances with isolated access control and zero third-party data selling.
            </p>
          </section>

          <section className="space-y-4 text-xs sm:text-sm leading-relaxed text-slate-600 border-t border-slate-100 pt-6">
            <h2 className="font-bold text-base text-slate-900">4. Contact Privacy Officer</h2>
            <p>If you have any questions regarding your account data or request data deletion, contact us at:</p>
            <div className="bg-slate-50 p-4 rounded-xl space-y-2 text-xs font-medium text-slate-700">
              <div className="flex items-center gap-2"><Mail className="w-4 h-4 text-[#2874f0]" /> Email: support@blessingpowerguide.in</div>
              <div className="flex items-center gap-2"><Phone className="w-4 h-4 text-[#2874f0]" /> WhatsApp Support: +91 9840418228</div>
              <div className="flex items-center gap-2"><MapPin className="w-4 h-4 text-[#2874f0]" /> Address: Main Express Logistics Hub, Tamil Nadu, India</div>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
